# Generated by Django 5.2.5 on 2025-08-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerapplication',
            name='message',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
