# Generated by Django 5.2.5 on 2025-08-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_careerapplication_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerapplication',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
