# Generated by Django 5.2.5 on 2025-08-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0003_alter_careerapplication_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerapplication',
            name='github_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
