# Generated by Django 5.2.5 on 2025-08-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0004_careerapplication_github_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerapplication',
            name='location',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
